name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cov:
      uses: ./.github/workflows/test_template.yml
      with:
        runs-on: '["ubuntu-latest", ]'
        coverage: true
        enable-viz-tests: true
        extra-depends: scikit-learn scipy statsmodels pandas tables fury tensorflow tensorflow-addons
      secrets:
        codecov-token: ${{ secrets.CODECOV_TOKEN }}